apiVersion: v1
kind: Service
metadata:
  name: dockerassignment-service
spec:
  type: NodePort
  selector:
    app: dockerassignment
  ports:
    - nodePort: 30165
      port: 8080
      protocol: TCP



